Add wildfly 10

diff --git a/php72/s2i/bin/assemble b/php72/s2i/bin/assemble
--- a/php72/s2i/bin/assemble
+++ b/php72/s2i/bin/assemble
@@ -8,10 +8,36 @@
 #
 
 set -e
-
+shopt -u dotglob
 DOCROOT="/var/www/html"
 SHARE="/usr/share/httpd"
-shopt -u dotglob
+
+
+
+function sonarqube() {
+
+
+if [[ "$SONARQUBE_ENABLED" == 1 ]]; then
+echo "----> SONARQUBE ACTIVADO."
+echo "----> VALIDANDO DATOS DE CONEXION.."
+
+if [[ -z "$SONARQUBE_HOST" ]] || [[ -z "$SONARQUBE_PROJECTKEY" ]] || [[ -z "$SONARQUBE_PROJECTNAME" ]]; then
+
+echo "----> ERROR NO SE ENCONTRARON LAS VARIABLES REQUERIDAS."
+echo "----> VERIFIQUE SONARQUBE_HOST, SONARQUBE_PROJECTNAME, SONARQUBE_PROJECTKEY."
+exit 1
+fi
+cd $DOCROOT && \
+composer require rogervila/php-sonarqube-scanner
+vendor/bin/sonar-scanner -Dsonar.projectKey=$SONARQUBE_PROJECTKEY -Dsonar.projectName=$SONARQUBE_PROJECTNAME \
+-Dsonar.exclusions="vendor/**, node_modules/**, .scannerwork/**" -Dsonar.sources=$DOCROOT -Dsonar.host.url=$SONARQUBE_HOST
+else 
+echo "----> SONARQUBE DESACTIVADO."
+fi
+
+
+}
+
 
 
 if [[ "$1" == "-h" ]]; then
@@ -26,10 +52,13 @@ fi
 fi
 
 
-
 echo "---> INSTALANDO CODIGO FUENTE..."
 cp -rf /tmp/src/.  $DOCROOT/
 rm -rf /tmp/src
+
+#### sonarqube function
+sonarqube
+#####
 
 if [[ -f "$DOCROOT/composer.json" ]]; then
 echo "----> COMPOSER ENCONTRADO!"
